## Lab Assignment: Numerical Computing using NumPy
Student:     **MICHAEL KAMP*

### Objective: To introduce numerical computing in Python using NumPy and understand NumPy arrays and operations.

### Instructions:
In this lab assignment, you will be introduced to numerical computing in Python using NumPy. You will learn how to create and manipulate NumPy arrays, perform mathematical operations on them, and apply built-in functions to analyze and transform the data.

You will be provided with the following five problems to solve. Please read the problem statement carefully and implement the solution using NumPy.

1. Create a 1D NumPy array of size 10, filled with zeros.
2. Create a 2D NumPy array with shape (3, 4), filled with random values.
3. Create a 3D NumPy array with shape (2, 3, 4), filled with ones.
4. Add two NumPy arrays element-wise.
5. Multiply two NumPy arrays element-wise.

### Deliverable:
Modify this notebook to include the python code as well as any documentation related to your submission.  Submit the notebook as your response in Blackboard.

### Grading Criteria:

Your lab assignment will be graded based on the following criteria:

- Correctness of the implementation
- Proper use of basic control structures and functions
- Code efficiency
- Clarity and readability of the code
- Compliance with the instructions and deliverables.

### Student Submission
1. Create a 1D NumPy array of size 10, filled with zeros.

In [1]:
import numpy as np
array_1d = np.zeros(10)
print(array_1d)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Create a 2D NumPy array with shape (3, 4), filled with random values.

In [9]:
import numpy as np
array_2d = np.random.rand(3, 4)  
print("2D array of random values:\n", array_2d)



2D array of random values:
 [[0.98049421 0.4996359  0.14729363 0.09319306]
 [0.79113378 0.35071157 0.60350291 0.98402877]
 [0.96745953 0.59228525 0.48720456 0.97796777]]


3. Create a 3D NumPy array with shape (2, 3, 4), filled with ones.

In [3]:
import numpy as np
array_3d = np.ones((2,3,4))
print("3D array of ones:\n", array_3d)

3D array of ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


4. Add two NumPy arrays element-wise.

In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
sum_array = a + b
print("element-wise sum:", sum_array)

element-wise sum: [5 7 9]


5. Multiply two NumPy arrays element-wise.

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
product_array = a * b
print("element-wise product:", product_array)

element-wise product: [ 4 10 18]
